DROP TABLE "MenuTable";

CREATE TABLE "MenuTable" (
	"MENUNAME"	VARCHAR2(20)		NOT NULL,
	"PRICE"	NUMBER		NOT NULL,
	"DESCRIPTION"	VARCHAR2(20)		NOT NULL,
	"SIZE"	NUMBER		NOT NULL
);

DROP TABLE "Non_memberTable";

CREATE TABLE "Non_memberTable" (
	"ORDERNUM"	NUMBER		NOT NULL
);

DROP TABLE "MemberTable";

CREATE TABLE "MemberTable" (
	"ID"	VARCHAR2(20)		NOT NULL,
	"PWD"	NUMBER		NOT NULL,
	"RESERVES"	NUMBER		NULL
);

DROP TABLE "OderTable";

CREATE TABLE "OderTable" (
	"ORDERNUM"	NUMBER		NOT NULL,
	"ORDERSELECT"	NUMBER		NOT NULL,
	"ORDERTIME"	VARCHAR(255)		NOT NULL,
	"MEMBERID"	VARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "OderTable"."ORDERSELECT" IS '배달주문 :1  포장주문 :2';

DROP TABLE "AddressTale";

CREATE TABLE "AddressTale" (
	"ORDERSHOP"	VARCHAR2(20)		NOT NULL,
	"DELIBERYPLACE"	VARCHAR2(20)		NULL,
	"ORDERNUM"	NUMBER		NOT NULL
);

DROP TABLE "Untitled";

CREATE TABLE "Untitled" (
	"ADDMENUID"	NUMBER		NOT NULL,
	"ADDMENUNAME"	VARCHAR2(20)		NULL
);

COMMENT ON COLUMN "Untitled"."ADDMENUID" IS '1:치즈 2:올리브 4:페페로니 64 128';

DROP TABLE "or";

CREATE TABLE "or" (
	"ORDERDATE"	DATE		NOT NULL,
	"QUANTITY"	NUMBER		NOT NULL,
	"ADDMENUID"	NUMBER		NOT NULL,
	"MENUNAME"	VARCHAR2(20)		NOT NULL,
	"ORDERNUM"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "or"."ADDMENUID" IS '1:치즈 2:올리브 4:페페로니 64 128';

ALTER TABLE "MenuTable" ADD CONSTRAINT "PK_MENUTABLE" PRIMARY KEY (
	"MENUNAME"
);

ALTER TABLE "MemberTable" ADD CONSTRAINT "PK_MEMBERTABLE" PRIMARY KEY (
	"ID"
);

ALTER TABLE "OderTable" ADD CONSTRAINT "PK_ODERTABLE" PRIMARY KEY (
	"ORDERNUM"
);

ALTER TABLE "Untitled" ADD CONSTRAINT "PK_UNTITLED" PRIMARY KEY (
	"ADDMENUID"
);

ALTER TABLE "Non_memberTable" ADD CONSTRAINT "FK_OderTable_TO_Non_memberTable_1" FOREIGN KEY (
	"ORDERNUM"
)
REFERENCES "OderTable" (
	"ORDERNUM"
);

ALTER TABLE "OderTable" ADD CONSTRAINT "FK_MemberTable_TO_OderTable_1" FOREIGN KEY (
	"MEMBERID"
)
REFERENCES "MemberTable" (
	"ID"
);

ALTER TABLE "AddressTale" ADD CONSTRAINT "FK_OderTable_TO_AddressTale_1" FOREIGN KEY (
	"ORDERNUM"
)
REFERENCES "OderTable" (
	"ORDERNUM"
);

ALTER TABLE "or" ADD CONSTRAINT "FK_Untitled_TO_or_1" FOREIGN KEY (
	"ADDMENUID"
)
REFERENCES "Untitled" (
	"ADDMENUID"
);

ALTER TABLE "or" ADD CONSTRAINT "FK_MenuTable_TO_or_1" FOREIGN KEY (
	"MENUNAME"
)
REFERENCES "MenuTable" (
	"MENUNAME"
);

ALTER TABLE "or" ADD CONSTRAINT "FK_OderTable_TO_or_1" FOREIGN KEY (
	"ORDERNUM"
)
REFERENCES "OderTable" (
	"ORDERNUM"
);

